on:
  pull_request_review:
    types: [submitted]

jobs:
  runs-on: windows-latest

  - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.1
      with:
        dotnet-version: 6.0.404

  - name: Install Paket as global tool
      run: dotnet tool install paket --global

  - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

  - name: Build and run
    run: npm run test
